### ISSUE TITLE
[Feature🚀] Add TraceView struct for rust

### ISSUE THREAD

**Issue by TeslaRustor** [mxsm/rocketmq-rust#1422]
### Is Your Feature Request Related to a Problem?

![image](https://github.com/user-attachments/assets/d2a33c45-bf5f-4d08-8f50-e622e52a00fb)
### Describe the Solution You'd Like

convert this to rust

**Comment by surajnuchin** [comment]
Hi @mxsm, 👋

I’ve been following the rocketmq-rust project for some time now, and I’m excited to contribute. I'd like to work on this issue as my first contribution.

To ensure I understand the requirements correctly, does this task involve migrating [TraceView.java](https://github.com/apache/rocketmq/blob/develop/client/src/main/java/org/apache/rocketmq/client/trace/TraceView.java) to Rust? Are there any additional details or considerations I should be aware of before I get started?

Thank you for your time and guidance! I’m looking forward to contributing. 😊

**Comment by mxsm** [comment]
@surajnuchin  Yes, Convert TraceView java class to rust struct, put this struct to 
![image](https://github.com/user-attachments/assets/ea67676a-575f-4188-8b77-3b02f79ff639)
welcome to contrubtion. Welcome to contribute code; you can work on the modules that you are interested in.
