### ISSUE TITLE
[Feature🚀] Add ConsumeRequest for ConsumeMessagePopConcurrentlyService

### ISSUE THREAD

**Issue by mxsm** [mxsm/rocketmq-rust#1653]

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added implementations for register_message_listener_concurrently and register_message_listener_orderly methods in the DefaultMQPushConsumer struct. These methods create a MessageListener instance with the provided listener, update the consumer_config, and register the listener with the default_mqpush_consumer_impl.

You can review changes in this commit: https://github.com/mnmnk43434/mxsm-rocketmq-rust-1653/commit/77290212648a32d7ef313a7a9fdcda07394f0327.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
