### ISSUE TITLE
[Enhancement⚡️] Add #[inline] for PutMessageResult methods

### ISSUE THREAD

**Issue by mxsm** [mxsm/rocketmq-rust#1689]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Summary

Add #[inline] for PutMessageResult methods

### Motivation

![image](https://github.com/user-attachments/assets/5007b710-5a01-43c1-b0d3-526075bb51ac)

**Comment by nakul-py** [comment]
Hi @mxsm 
I came across this issue and would like to work on resolving it. Could you please assign it to me?

**Comment by mxsm** [comment]
> Hi @mxsm I came across this issue and would like to work on resolving it. Could you please assign it to me?

@nakul-py  sure!
