### ISSUE TITLE
[Enhancement⚡️] Add #[inline] for SendResult struct methods

### ISSUE THREAD

**Issue by mxsm** [mxsm/rocketmq-rust#1714]
### Before Creating the Enhancement Request

- [X] I have confirmed that this should be classified as an enhancement rather than a bug/feature.

### Motivation

![image](https://github.com/user-attachments/assets/3af98005-79f3-4a06-a375-6906ecaabda9)

**Comment by ad-source-bit** [comment]
I want to try

**Comment by mxsm** [comment]
> I want to try

@ad-source-bit  sure!
