### ISSUE TITLE
[Feature]Namesrv support update namesrv config (request code 318)

### ISSUE THREAD

**Issue by mxsm** [mxsm/rocketmq-rust#90]
Namesrv support update namesrv config (request code 318)

**Comment by PanGan21** [comment]
Hey this project seems quite interesting. Could you share some information about this task to give a try in my free time?

**Comment by mxsm** [comment]
@PanGan21 Welcome to rocketmq-rust, a project that aims to re-implement Apache RocketMQ's Java version using Rust. In the DefaultRequestProcessor of the Apache RocketMQ Java version, you can look at the method corresponding to request code 318, which is `updateConfig`. 
![image](https://github.com/user-attachments/assets/767fdd01-5659-4778-b392-ad1014fd4ff4)
This function is primarily used to update the configuration of the Name Server. In the Rust version, you can write the code within the `DefaultRequestProcessor` struct under the `rocketmq-namesrv` directory. 
![image](https://github.com/user-attachments/assets/5df2c25c-22a5-42c9-b9dc-613da7c30368)

More related tasks will be updated in the ISSUE section going forward. If you are interested in rocketmq-rust, we welcome your ongoing contributions.

**Comment by PanGan21** [comment]
Hi @mxsm I did some initial implementation of this at #1316 . It would be nice to get some feedback
